'use strict'

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        /**
         * Add seed commands here.
         *
         * Example:
         * await queryInterface.bulkInsert('People', [{
         *   name: 'John Doe',
         *   isBetaMember: false
         * }], {});
         */
        await queryInterface.sequelize.query(`
        INSERT INTO "public"."pages" ("id", "picture", "date", "category_id", "slug", "title", "content", "createdAt", "updatedAt") VALUES (2, 'uploads/1699204354536', '2023-11-06 00:12:34+07', 4, 'apa-itu-cop28-di-dubai-dan-mengapa-itu-penting', 'Apa Itu COP28 di Dubai dan Mengapa Itu Penting?', 'konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten ', '2023-11-06 00:12:37.33+07', '2023-11-06 00:12:37.33+07');
        INSERT INTO "public"."pages" ("id", "picture", "date", "category_id", "slug", "title", "content", "createdAt", "updatedAt") VALUES (3, 'uploads/1699204403135', '2023-11-06 00:13:23+07', 1, 'beberapa-negara-ini-diprediksi-tak-layak-huni-karena-cuaca-panas', 'Beberapa Negara Ini Diprediksi Tak Layak Huni Karena Cuaca Panas', 'konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten ', '2023-11-06 00:13:26.761+07', '2023-11-06 00:13:26.761+07');
        INSERT INTO "public"."pages" ("id", "picture", "date", "category_id", "slug", "title", "content", "createdAt", "updatedAt") VALUES (4, 'uploads/1699204475423', '2023-11-06 00:14:35+07', 2, 'instagram-uji-fitur-baru-bikin-stiker-dari-foto-kapan-rilis', 'Instagram Uji Fitur Baru Bikin Stiker dari Foto, Kapan Rilis?', 'konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten ', '2023-11-06 00:14:37.894+07', '2023-11-06 00:14:37.894+07');
        INSERT INTO "public"."pages" ("id", "picture", "date", "category_id", "slug", "title", "content", "createdAt", "updatedAt") VALUES (5, 'uploads/1699204512532', '2023-11-06 00:15:12+07', 4, 'ini-sungai-tergelap-di-dunia-airnya-seperti-tercampur-minyak-mentah', 'Ini Sungai Tergelap di Dunia, Airnya seperti Tercampur Minyak Mentah', 'konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten konten ', '2023-11-06 00:15:15.662+07', '2023-11-06 00:15:15.662+07');
        INSERT INTO "public"."pages" ("id", "picture", "date", "category_id", "slug", "title", "content", "createdAt", "updatedAt") VALUES (1, 'uploads/1699204301095', '2023-11-28 14:30:20+07', 5, 'apa-yang-terjadi-pada-tubuh-jika-berada-di-luar-angkasa-tanpa-baju-astronaut', 'Apa yang Terjadi pada Tubuh jika Berada di Luar Angkasa Tanpa Baju Astronaut?', '![](http://localhost:3000/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdxnewldiy%2Fimage%2Fupload%2Fv1695634913%2Fuploads%2F1699204301095&w=256&q=75)', '2023-11-06 00:11:43.954+07', '2023-11-28 14:30:20.145+07');
   `)
    },

    async down(queryInterface, Sequelize) {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
    },
}
